Fix error while converting to non-pointer type.
Details of the issue:

/home/travis/build/johnwbyrd/logog/include/thread.hpp:82:18: error: converting to non-pointer type `pthread_t {aka long unsigned int}` from NULL [-Werror=conversion-null]
         m_Thread = NULL;

Tests:

+ Windows 10
- Success running "test-logog.exe"

+ macOS Catalina 10.15.7
- Success running "mkdir build && mkdir build/Debug && mkdir build/Release && cd build/Debug && cmake -DCMAKE_BUILD_TYPE=Debug ../.. && make && ctest -VV -C Debug && cd ../Release && cmake -DCMAKE_BUILD_TYPE=Release ../.. && make && ctest -VV -C Release"